apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: ontap-nas-no-snapshot
  name: db-backup-influxdb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi